name: Feature
description: File a new feature request
title: "FEATURE[] <title>"
labels: [feature, Needs Triage]
body:
- type: textarea
  attributes:
    label: Current Problem 
    description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: false
- type: textarea
  attributes:
    label: Proposed Solution
    description: A concise description of what you want to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Alternatives
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Adittional context
    description: |
      Links? References? Add any other context or screenshots about the feature request here.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
